name: itmo_cloud_technology
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.14.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.21.0
dependencies:
  intl: ^0.18.0
  convert: ^3.0.1
